# Generated by Django 5.0.2 on 2024-02-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('pages', '0002_remove_compte_username_compte_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compte'),
        ),
    ]
