# Generated by Django 5.0.2 on 2024-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='username',
        ),
        migrations.AddField(
            model_name='compte',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='userName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
