# Generated by Django 5.0.2 on 2024-02-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_auteur'),
        ('pages', '0002_remove_compte_username_compte_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compte',
        ),
    ]
